# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06b7af95cfed59c9d3809e1e0b929266c2b7ac7553550495c767932a7f3e2a06083219d463572b20b75c058881f0302c82df9aa467bb776853beaa49fffceb33

test:
  secret_key_base: bdd05937468c675edb3482eb247a10428f60c5282f088bd9b779a69d10ea84993b86e56f77cce9f831c1d603d7c278f37cc27fadf5f56893da0a676221ba98c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
